=== AnyaKarpiuk/JSONProject/JSONProject/CoffeeSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "Coffee.json",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "description": "The name of coffee",
                "type": "string",
                "minLength": 3,
                "maxlength": 10
            },
            "subname": {
                "description": "The additional name",
                "type": "string",
                "minLength": 3,
                "maxlength": 10
            },
            "shotTime": {
                "description": "The number of seconds needed for extracting coffee",
                "type": "integer",
                "minimum": 0,
                "maximum": 30
            },
            "cupSize": {
                "description": "The size of a cup measured in miligrams",
                "type": "integer",
                "minimum": 0,
                "maximum": 900
            },
            "ingredients": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "water": {
                            "type": "boolean"
                        },
                        "amount": {
                            "description": "The amount of water in percentage",
                            "type": "integer",
                            "minimum": 0,
                            "maximum": 100
                        }
                    },
                    "type": "object",
                    "properties": {
                        "milk": {
                            "type": "boolean"
                        },
                        "amount": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "milkAmount": {
                                        "description": "The amount of warm milk in percentage",
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 100
                                    },
                                    "foamAmount": {
                                        "description": "The amount of foam in percentage",
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 100
                                    }
                                }
                            }
                        }
                    },
                    "type": "object",
                    "properties": {
                        "chocolate": {
                            "type": "boolean"
                        },
                        "amount": {
                            "description": "The amount of chocolate in percentage",
                            "type": "integer",
                            "minimum": 0,
                            "maximum": 100
                        }
                    },
                    "type": "object",
                    "properties": {
                        "additionalIngredients": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "minLength": 1,
                                "maxlength": 20
                            },
                            "minItems": 1,
                            "uniqueItems": true,
                            "pattern": "[a-zA-Z]"
                        }
                    }
                }
            },
            "instruction": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "stepOne": {
                            "type": "string",
                            "minLength": 10,
                            "maxlength": 30
                        },
                        "stepTwo": {
                            "type": "string",
                            "minLength": 10,
                            "maxlength": 30
                        },
                        "stepThree": {
                            "type": "string",
                            "minLength": 10,
                            "maxlength": 30
                        }
                    },
                    "required": [
                        "stepOne"
                    ]
                }
            },
            "coffeeArt": {
                "type": "boolean"
            }
        },
        "required": [
            "name",
            "shotTime",
            "cupSize",
            "instruction"
        ]
    }
}

=== AnyaKarpiuk/JSONProject/JSONProject/Coffee.json
[
    {
        "name": "Macchiato",
        "subname": "Single",
        "shotTime": 24,
        "cupSize": 100,
        "ingredients": [
            {
                "milk": true,
                "amount": [
                    {
                        "foamAmount": 10
                    }
                ]
            }
        ],
        "instruction": [
            {
                "stepOne": "Extract single shot of coffee.",
                "stepTwo": "Steam milk.",
                "stepThree": "Add few spoons of foam on a top."
            }
        ]
    },
    {
        "name": "Macchiato",
        "subname": "Double",
        "shotTime": 24,
        "cupSize": 150,
        "ingredients": [
            {
                "milk": true,
                "amount": [
                    {
                        "foamAmount": 10
                    }
                ]
            }
        ],
        "instruction": [
            {
                "stepOne": "Extract double shot of coffee.",
                "stepTwo": "Steam milk.",
                "stepThree": "Add few spoons of foam on a top."
            }
        ]
    },
    {
        "name": "Ristretto",
        "shotTime": 17,
        "cupSize": 100,
        "instruction": [
            {
                "stepOne": "When extraction double shot of coffee press a button stop after 17 seconds."
            }
        ]
    },
    {
        "name": "Americano",
        "subname": "Black",
        "shotTime": 24,
        "cupSize": 300,
        "ingredients": [
            {
                "water": true,
                "amount": 70
            }
        ],
        "instruction": [
            {
                "stepOne": "Extract double shot of coffee.",
                "stepTwo": "Add hot water."
            }
        ]
    },
    {
        "name": "Americano",
        "subname": "White",
        "shotTime": 24,
        "cupSize": 300,
        "ingredients": [
            {
                "water": true,
                "amount": 70
            },
            {
                "milk": true,
                "amount": [
                    {
                        "milkAmount": 5
                    }
                ]
            }
        ],
        "instruction": [
            {
                "stepOne": "Extract double shot of coffee.",
                "stepTwo": "Add hot water.",
                "stepThree": "Add splash of hot milk."
            }
        ]
    },
    {
        "name": "Latte",
        "shotTime": 24,
        "cupSize": 300,
        "ingredients": [
            {
                "milk": true,
                "amount": [
                    {
                        "milkAmount": 50,
                        "foamAmount": 20
                    }
                ]
            },
            {
                "additionalIngredients": [
                    "syrops",
                    "cinnamon"
                ]
            }
        ],
        "instruction": [
            {
                "stepOne": "Extract double shot of coffee.",
                "stepTwo": "Steam milk, leaving a steamer on a top for 3 seconds.",
                "stepThree": "Pour milk in a cup and after slowly add a shot of coffee."
            }
        ],
        "coffeeArt": true
    },
    {
        "name": "Cappuccino",
        "shotTime": 24,
        "cupSize": 300,
        "ingredients": [
            {
                "milk": true,
                "amount": [
                    {
                        "milkAmount": 20,
                        "foamAmount": 50
                    }
                ]
            },
            {
                "additionalIngredients": [
                    "syrops",
                    "chocolate"
                ]
            }
        ],
        "instruction": [
            {
                "stepOne": "Extract double shot of coffee.",
                "stepTwo": "Steam milk, leaving a steamer on a top for 10 seconds.",
                "stepThree": "Add steamed milk in a cup with a shot."
            }
        ],
        "coffeeArt": true
    },
    {
        "name": "Mocha",
        "shotTime": 24,
        "cupSize": 300,
        "ingredients": [
            {
                "milk": true,
                "amount": [
                    {
                        "milkAmount": 50,
                        "foamAmount": 20
                    }
                ]
            },
            {
                "chocolate": true,
                "amount": 2
            },
            {
                "additionalIngredients": [
                    "syrops",
                    "marshmallows"
                ]
            }
        ],
        "instruction": [
            {
                "stepOne": "Extract double shot of coffee and mix it with chocolate until it dissolves.",
                "stepTwo": "Steam milk, leaving a steamer on a top for 3 seconds.",
                "stepThree": "Pour milk in a cup with coffee and chocolate."
            }
        ],
        "coffeeArt": true
    }
]
